spring:
  application:
    name: orderservice
  profiles:
    active: default
  zipkin:
    baseUrl: http://localhost:9411
server:
  port: 8092


eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    preferIpAddress: true
    ipAddress: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout: true
            interruptOnCancel: false
        timeout:
          enabled: true
  metrics:
    enabled: true
  threadpool:
    productservice:
      coreSize: 10
      maxQueueSize: 20

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
