spring:
  application:
    name: zuulservice
  zipkin:
    baseUrl: http://localhost:9411
server:
  port: 5555

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  #To force the original encoding of the query string
  forceOriginalQueryStringEncoding: true
  routes:
    orderservice:
      path: /order/**
    productservice:
      path: /product/**
  retryable: true


ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #请求处理的时间，默认1秒
  ReadTimeout: 3000
  #请求连接的超时时间,缺省1秒
  ConnectTimeout: 1000