spring:
  application:
    name: productservice
  profiles:
    active: default
  zipkin:
    baseUrl: http://localhost:9411
server:
  port: 8082


eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    # 设置微服务调用地址为IP优先（缺省为false）
    preferIpAddress: true
    ipAddress: localhost
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    leaseRenewalIntervalInSeconds: 30
    # 发呆时间，即服务续约到期时间（缺省为90s）
    leaseExpirationDurationInSeconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
    healthcheck:
      enabled: true

logging:
  config: classpath:config/logback-spring.xml