spring:
  application:
    name: eureka-server
server:
  port: ${server.port}
eureka:
  instance:
    hostname: ${eureka.host}
  client:
    #    serviceUrl:
    #      defaultZone: http://peer2:8762/eureka/
    fetchRegistry: false
    registerWithEureka: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
