spring:
  application:
    name: eureka-server
eureka:
  instance:
    instance-id: eureka-1
    prefer-ip-address: true
  client:
    #    serviceUrl:
    #      defaultZone: http://peer2:8762/eureka/
    fetchRegistry: false
    registerWithEureka: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
