version: "3.7"

services:
    logstash:
        image: logstash:7.5.1
        volumes:
            - ./logstash.conf:/etc/logstash.conf
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
        depends_on:
            - elasticsearch
        command:
            -f /etc/logstash.conf


    elasticsearch:
        image: elasticsearch:7.5.1
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        
    kibana:
        image: kibana:7.5.1
        depends_on: 
            - elasticsearch
        ports:
            - "5601:5601"